// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_maas

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func MaasProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type MaasModel struct {
}
