// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_tag

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func TagResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"comment": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A description of what fhe tag will be used for in natural language.",
				MarkdownDescription: "A description of what fhe tag will be used for in natural language.",
				Default:             stringdefault.StaticString(""),
			},
			"definition": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "An XPATH query that is evaluated againstthe hardware_details stored for all nodes (i.e. the output of ``lshw -xml``).",
				MarkdownDescription: "An XPATH query that is evaluated againstthe hardware_details stored for all nodes (i.e. the output of ``lshw -xml``).",
				Default:             stringdefault.StaticString(""),
			},
			"id": schema.Int64Attribute{
				Computed: true,
			},
			"kernel_opts": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Nodes associated with this tag will add this string to their kernel options when booting. The value overrides the global ``kernel_opts`` setting. If more than one tag is associated with a node, command line will be concatenated from all associated tags, in alphabetic tag name order.",
				MarkdownDescription: "Nodes associated with this tag will add this string to their kernel options when booting. The value overrides the global ``kernel_opts`` setting. If more than one tag is associated with a node, command line will be concatenated from all associated tags, in alphabetic tag name order.",
				Default:             stringdefault.StaticString(""),
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The new tag name. Because the name will be used in urls, it should be short.",
				MarkdownDescription: "The new tag name. Because the name will be used in urls, it should be short.",
			},
		},
	}
}

type TagModel struct {
	Comment    types.String `tfsdk:"comment"`
	Definition types.String `tfsdk:"definition"`
	Id         types.Int64  `tfsdk:"id"`
	KernelOpts types.String `tfsdk:"kernel_opts"`
	Name       types.String `tfsdk:"name"`
}
