// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_fabric

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func FabricResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"class_type": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The description of the fabric.",
				MarkdownDescription: "The description of the fabric.",
				Default:             stringdefault.StaticString(""),
			},
			"fabric_id": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"id": schema.Int64Attribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The unique name of the entity.",
				MarkdownDescription: "The unique name of the entity.",
			},
		},
	}
}

type FabricModel struct {
	ClassType   types.String `tfsdk:"class_type"`
	Description types.String `tfsdk:"description"`
	FabricId    types.Int64  `tfsdk:"fabric_id"`
	Id          types.Int64  `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
}
